### PR TITLE
Images and Links Changed

### PR DESCRIPTION
**Pull request by roverflow**
Signed-off-by: roverflow <63404819+roverflow@users.noreply.github.com>

Description : 
Have made changes to the images and links

### CODE REVIEW

**Comment by adithyaakrishna** [comment]
@uravgkarthik Here's the Preview For this PR

https://deploy-preview-4--jithack.netlify.app/

**Comment by adithyaakrishna** [comment]
@roverflow Amazing Work 🎉💯

**Review by adithyaakrishna — APPROVED** [review]

**Comment by uravgkarthik** [comment]
Good job team
However, I see the button overlapping

**Comment by roverflow** [comment]
> 
> 
> Good job team
> However, I see the button overlapping!
> 
> 

will try fixing it as soon as possible

**Comment by uravgkarthik** [comment]
> > 
> > 
> > Good job team
> > However, I see the button overlapping!
> > 
> > 
> 
> will try fixing it as soon as possible
> 

No problem, take your time
Also, do verify if the same issue persists on your device.

**Comment by roverflow** [comment]
> 
> 
> > > Good job team
> > > However, I see the button overlapping!
> > > 
> > 
> > 
> > will try fixing it as soon as possible
> 
> No problem, take your time
> Also, do verify if the same issue persists on your device.

just checked , it is happening only on mobile devices , will try to fix

**Comment by uravgkarthik** [comment]
> > 
> > 
> > > > Good job team
> > > > However, I see the button overlapping!
> > > > 
> > > 
> > > 
> > > will try fixing it as soon as possible
> > 
> > No problem, take your time
> > Also, do verify if the same issue persists on your device.
> 
> just checked , it is happening only on mobile devices , will try to fix 
> 

Cool

**Comment by adithyaakrishna** [comment]
@roverflow LGTM 🙌

**Comment by uravgkarthik** [comment]
Just noticed that the first two questions in the FAQ show the answer by themselves. Please take a note of that and do try to fix it.

**Comment by adithyaakrishna** [comment]
@uravgkarthik Fixed in the latest commit 92f764ea78e89aa58d308305f85f177b871282e9

**Comment by adithyaakrishna** [comment]
@uravgkarthik If any issue has come to notice from next time onwards, please do comment in the open PRs as the merged and closed ones cannot be updated further or drop a message about the same on the group 🚀

**Pull request merged**
